### PR TITLE
Changed the eyeColor extraction logic to use the IconUrl instead of MaskUrl field

### PR DESCRIPTION
**Pull request by gadamyan**
## [TICKETID](https://ready-player-me.atlassian.net/browse/TICKETID)

Screenshot 2023-11-22 130143

## Description

-   Changed the eyeColor extraction logic to use the IconUrl instead of the MaskUrl field
-   Adjusted the padding in the widgets and removed the EyeColorMask material.

#### Updated

-   Changed the eyeColor extraction logic to use the IconUrl instead of the MaskUrl field
-   Adjusted the padding in the widgets and removed the EyeColorMask material.

## Checklist

-   [ ] Changelog is updated.

### CODE REVIEW

**Comment by MaxAndreassenRPM** [comment]
Can we get a screenshot of the UI change and/or any blueprints changes?

**Review by HarrisonHough — APPROVED** [review]
All good, seems to work! It's kinda nice we don't have to deal with masking sdk side

**Comment by gadamyan** [comment]
> All good, seems to work! It's kinda nice we don't have to deal with masking sdk side

Fixing the workarounds one-by-one

**Comment by gadamyan** [comment]
> Can we get a screenshot of the UI change and/or any blueprints changes?

Almost no blueprint changes, only UI changes to adjust the size.

**Pull request merged**
