### PR TITLE
[SDK-590] AppId mandatory in setup guide

### PR DESCRIPTION
**Pull request by gadamyan**
## Description

-   Removed the demo subdomain checkbox from the setup guide

#### Removed

-   Removed the demo subdomain checkbox from the setup guide

image

[SDK-590]: https://ready-player-me.atlassian.net/browse/SDK-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

## Old

Screenshot 2023-11-16 211145

Screenshot 2023-11-16 211118

Screenshot 2023-11-16 211214

## New

Screenshot 2023-11-16 210913

Screenshot 2023-11-16 211414

### CODE REVIEW

**Review by HarrisonHough — COMMENTED** [review]
Not sure if its just me but I'm unable to run this branch locally? 
image

**Review by HarrisonHough — CHANGES_REQUESTED** [review]
Yo I checked with Bernhard, we should have a question mark button next to app id that links to the same paragraph in the docs 
Also, if you can rename `subdomain` to `Subdomain` and `app ID` to `App ID` that would be amazeballs
image

**Comment by gadamyan** [comment]
> Yo I checked with Bernhard, we should have a question mark button next to app id that links to the same paragraph in the docs Also, if you can rename `subdomain` to `Subdomain` and `app ID` to `App ID` that would be amazeballs image

If you can send me the link for the AppId, I can add it.
I intentionally made  it lowercase so that people wouldn't  put  the subdomain with Upper case

**Comment by gadamyan** [comment]
> Yo I checked with Bernhard, we should have a question mark button next to app id that links to the same paragraph in the docs Also, if you can rename `subdomain` to `Subdomain` and `app ID` to `App ID` that would be amazeballs image

Done

**Review by HarrisonHough — APPROVED** [review]
Looks good now. Nice work!

**Pull request merged**
